<a href="https://colab.research.google.com/github/Tuevu110405/Module4-Linear_regression/blob/feature%2Fsales_prediction/sales_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
class CustomLinearRegression:
    def __init__(self, X_data, y_target, learning_rate = 0.01, num_epochs = 10000):
        self.num_samples = X_data.shape[0]
        self.X_data = np.c_[np.ones((self.num_samples, 1)), X_data]
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs

        #Initialize weights
        self.theta = np.random.randn(self.X_data.shape[1], 1)
        self.losses = []

    def compute_loss(self, y_pred, y_target):
        return (1 / 2 * self.num_samples) * np.sum(np.square(y_pred - self.y_target))

    def predict(self, X_data):
        y_pred = X_data.dot(self.theta)
        return y_pred

    def fit(self):
        for epoch in range(self.num.epochs):
            # predict
            y_pred = self.predict(self.X_data)

            # compute loss
            loss = self.compute_loss(y_pred, self.y_target)
            self.losses.append(loss)

            #compute gradient
            loss_grd = 2*(y_pred - self.y_target)/ self.num_samples
            gradients = self.X_data.T.dot(loss_grd)

            #update weights
            self.theta -= self.learning_rate * gradients

        return self.theta, self.losses

In [ ]:
def r2score(y_pred, y):
    rss = np.sum(np.square(y - y_pred))
    tss = np.sum(np.square(y - np.mean(y)))
    r2 = 1 - (rss/tss)
    return r2

In [ ]:
#Case 1
y_pred = np.array([1, 2, 3, 4, 5])
y = np.array([3,5,5,2,4])
r2score(y_pred, y)

-2.235294117647059

In [ ]:
def create_polynomial_feature(X, degree = 2):
    X_new = X
    for i in range(2, degree + 1):
        X_new = np.c_[X_new, np.power(X, i)]
    return X_new

x = np.array([1,2,3,4,5])
print(x)
print(x.shape)
create_polynomial_feature(x, 2)

[1 2 3 4 5]
(5,)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [ ]:
def create_polynomial_features(X, degree = 2):
    X_mem = []
    for X_sub in X.T:
        X_new = X_sub.T
        for i in range(2, degree + 1):
            X_new = np.c_[X_new, np.power(X_sub, i)]
        X_mem.extend(X_new.T)
    print(X_mem[0].shape)
    return np.c_[ X_mem ].T

In [ ]:
X = np.array([[1 , 2] ,
[2 , 3] ,
[3 , 4]])

A = create_polynomial_features(X,degree =2)
print(A)

(3,)
[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]

In [1]:
!gdown 1A8kK0IEsT3w8htzU18ihFr5UV-euhquC

Downloading...
From: https://drive.google.com/uc?id=1A8kK0IEsT3w8htzU18ihFr5UV-euhquC
To: /content/SalesPrediction.csv
100% 206k/206k [00:00<00:00, 30.7MB/s]

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('SalesPrediction.csv')
df.head()

     TV      Radio  Social Media Influencer       Sales
0  16.0   6.566231      2.907983       Mega   54.732757
1  13.0   9.237765      2.409567       Mega   46.677897
2  41.0  15.886446      2.913410       Mega  150.177829
3  83.0  30.020028      6.922304       Mega  298.246340
4  15.0   8.437408      1.405998      Micro   56.594181

In [4]:

df = pd.get_dummies(df)
df.head()

,TV,Radio,Social Media,Sales,Influencer_Macro,Influencer_Mega,Influencer_Micro,Influencer_Nano
0,16.0,6.566231,2.907983,54.732757,False,True,False,False
1,13.0,9.237765,2.409567,46.677897,False,True,False,False
2,41.0,15.886446,2.913410,150.177829,False,True,False,False
3,83.0,30.020028,6.922304,298.246340,False,True,False,False
4,15.0,8.437408,1.405998,56.594181,False,False,True,False

In [6]:
#Handle Null values
df = df.fillna(df.mean())

#Get features
X = df[['TV', 'Radio', 'Social Media', 'Influencer_Macro', 'Influencer_Micro']]
y = df[['Sales']]

#Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)

In [9]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_processed = scaler.fit_transform(X_train)
X_test_processed = scaler.transform(X_test)
scaler.mean_[0]

54.173577723283785

In [10]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree = 2)
X_train_poly = poly_features.fit_transform(X_train_processed)
X_test_poly = poly_features.transform(X_test_processed)

In [12]:
#Training and evaluation
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)

preds = poly_model.predict(X_test_poly)
r2_score(y_test, preds)

0.995203916593938